services:
  postgres:
    build: ./db
    shm_size: 128mb
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: postgres
  main:
    build: ./
    init: true
    ports:
      - "3000:3000"
    env_file:
      - .env
